import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
     return (
      <>
         <Head>
        <title>Nift NFT Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
       <Component {...pageProps} />
      </>
     )
}
